apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-app
type: Opaque
data:
  POSTGRES_USER: dXN1YXJpbw==        # "usuario" en base64
  POSTGRES_PASSWORD: Y2xhdmU=        # "clave" en base64
  POSTGRES_DB: ZWplbXBsbw==         # "ejemplo" en base64
